# Clock and Shift Operators

Amelie Schreiber
I would like to know what the clock and shift operators of quantum mechanics are. 
As an AI language model, I can explain the concept of the shift operator in quantum mechanics.

In quantum mechanics, the shift operator is a mathematical operator that shifts the position of a wavefunction. It is used to represent the effect of a translation of the system under study.

The shift operator is defined as:

S(a)ψ(x) = ψ(x-a)

where a is a constant representing the amount of shift and ψ(x) is the wavefunction at position x.

The shift operator can be used to represent a translation of a particle in space, for example, in a crystal lattice. It can also be used to shift the position of a wavefunction in time, which is known as the clock operator.

The clock operator, on the other hand, is a mathematical operator that shifts the phase of a wavefunction. It is used to represent the effect of a time evolution of the system under study.

The clock operator is defined as:

C(t)ψ(x) = e^(-iEt/ħ)ψ(x)

where t is a constant representing the amount of time and E is the energy of the system.

The clock operator can be used to represent the evolution of a system in time, for example, in a quantum mechanical system. It is also used to represent the effect of a time-dependent perturbation on a system.




Amelie Schreiber
I would like to understand the matrix versions of the clock and shift operator applied to a qudit of dimension n. Can you please give me the matrix forms of these operators. 
Sure! The shift operator and the clock operator for a qudit of dimension n can be expressed as matrices.

The matrix form of the shift operator S for a qudit of dimension n is an n-by-n matrix with elements:

(S){i,j} = δ{i,j-1}

where δ is the Kronecker delta function.

The matrix form of the clock operator C for a qudit of dimension n is also an n-by-n matrix with elements:

(C)_{i,j} = e^{2πi(j-1)(i-1)/n}

where i and j are indices running from 1 to n.

The shift operator S and the clock operator C satisfy the following commutation relation:

SC = e^{2πi/n} CS

where e is the base of the natural logarithm.

These operators are very useful in quantum information processing and quantum algorithms, particularly in quantum Fourier transforms and phase estimation algorithms.




Amelie Schreiber
Please print LaTeX code to construct these two matrix operator. 
Sure! Here's the LaTeX code to construct the shift operator and the clock operator matrices for a qudit of dimension n:

Shift operator matrix:

$$
S =
\begin{pmatrix}
0 & 1 & 0 & \cdots & 0 \\
0 & 0 & 1 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & 1 \\
1 & 0 & 0 & \cdots & 0
\end{pmatrix}
$$

Clock operator matrix:

$$
C =
\begin{pmatrix}
1 & 1 & 1 & \cdots & 1 \\
1 & e^{2πi/n} & e^{4πi/n} & \cdots & e^{2(n-1)πi/n} \\
1 & e^{4πi/n} & e^{8πi/n} & \cdots & e^{4(n-1)πi/n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & e^{2(n-1)πi/n} & e^{4(n-1)πi/n} & \cdots & e^{2(n-1)^2πi/n}
\end{pmatrix}
$$

In [1]:
import cirq
import numpy as np

def get_shift_matrix(n: int) -> np.ndarray:
    S = np.zeros((n, n), dtype=np.complex128)
    for i in range(n):
        S[(i + 1) % n][i] = 1
    return S

def get_clock_matrix(n: int) -> np.ndarray:
    C = np.zeros((n, n), dtype=np.complex128)
    for i in range(n):
        for j in range(n):
            C[i][j] = np.exp(2j * np.pi * i * j / n)
    return C

# Test the code for n = 3
n = 5
S = get_shift_matrix(n)
C = get_clock_matrix(n)
print(f"Shift matrix:\n{S}\n")
print(f"Clock matrix:\n{C}\n")


Shift matrix:
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]]

Clock matrix:
[[ 1.        +0.j          1.        +0.j          1.        +0.j
   1.        +0.j          1.        +0.j        ]
 [ 1.        +0.j          0.30901699+0.95105652j -0.80901699+0.58778525j
  -0.80901699-0.58778525j  0.30901699-0.95105652j]
 [ 1.        +0.j         -0.80901699+0.58778525j  0.30901699-0.95105652j
   0.30901699+0.95105652j -0.80901699-0.58778525j]
 [ 1.        +0.j         -0.80901699-0.58778525j  0.30901699+0.95105652j
   0.30901699-0.95105652j -0.80901699+0.58778525j]
 [ 1.        +0.j          0.30901699-0.95105652j -0.80901699-0.58778525j
  -0.80901699+0.58778525j  0.30901699+0.95105652j]]



Here, I had to start a new conversation as ChatGPT got stuck on reproducing these results. 

Amelie Schreiber:

Please give me the general form of the clock and shift matrix from quantum mechanics.
In quantum mechanics, the clock matrix and shift matrix are two important operators that arise in the study of quantum systems with periodic boundary conditions.

ChatGPT:

The clock matrix is denoted by $C$ and is a diagonal matrix with entries $e^{2\pi i n/N}$, where $n$ runs from $0$ to $N-1$ and $N$ is the size of the system. In other words, the diagonal entries of the clock matrix are the $N$th roots of unity. The general form of the clock matrix is:

$$
\begin{pmatrix}
1 & 0 & 0 & \cdots & 0 \\
0 & e^{2\pi i/N} & 0 & \cdots & 0 \\
0 & 0 & e^{4\pi i/N} & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & e^{2\pi i (N-1)/N} \\
\end{pmatrix} $$

The shift matrix, denoted by $S$, is a unitary matrix that shifts the wavefunction of the system by one lattice site. The general form of the shift matrix is:

$$ S = \begin{pmatrix}
0 & 1 & 0 & \cdots & 0 \\
0 & 0 & 1 & \cdots & 0 \\
0 & 0 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & 0 & 0 & \cdots & 0 \\
\end{pmatrix} $$

Note that the shift matrix is a cyclic permutation matrix that corresponds to shifting the system by one site, while the clock matrix contains information about the periodicity of the system. Together, the clock and shift matrices generate the so-called "Heisenberg group," which is a fundamental mathematical structure that arises in the study of quantum mechanics on periodic lattices.

Amelie Schreiber:

Please implement Cirq code to take as input the dimension n, and give as output the clock and shift matrix as operators on a qudit of dimension n. 

In [2]:
import cirq
import numpy as np

def clock_shift_matrices(n: int):
    # Define the clock matrix
    clock_mat = np.zeros((n, n), dtype=np.complex128)
    for i in range(n):
        clock_mat[i, i] = np.exp(2j * np.pi * i / n)
    clock_op = cirq.MatrixGate(clock_mat)

    # Define the shift matrix
    shift_mat = np.roll(np.eye(n), -1, axis=0)
    shift_op = cirq.MatrixGate(shift_mat)

    return clock_op, shift_op


In [3]:
n = 3
clock_op, shift_op = clock_shift_matrices(n)

print("Clock matrix:\n", cirq.unitary(clock_op))
print("Shift matrix:\n", cirq.unitary(shift_op))


ValueError: Matrix width (3) is not a power of 2 and qid_shape is not specified.

ChatGPT:

I apologize for the error. The cirq.MatrixGate class expects the matrix dimensions to be a power of two by default, which is not the case for the clock and shift matrices. To fix this, we can explicitly specify the qid_shape argument when creating the MatrixGate objects to inform Cirq that the matrices act on a qudit of dimension n.

Here is the modified implementation of the clock_shift_matrices function:

In [4]:
import cirq
import numpy as np

def clock_shift_matrices(n: int):
    # Define the clock matrix
    clock_mat = np.zeros((n, n), dtype=np.complex128)
    for i in range(n):
        clock_mat[i, i] = np.exp(2j * np.pi * i / n)
    clock_op = cirq.MatrixGate(clock_mat, qid_shape=(n,))

    # Define the shift matrix
    shift_mat = np.roll(np.eye(n), -1, axis=0)
    shift_op = cirq.MatrixGate(shift_mat, qid_shape=(n,))

    return clock_op, shift_op


The only change we made is to add the qid_shape argument with value (n,) to the MatrixGate constructor.

You can now use the clock_shift_matrices function as before, with the modification that the MatrixGate objects have qid_shape set to (n,). Here's an example usage:

In [5]:
n = 5
clock_op, shift_op = clock_shift_matrices(n)

print("Clock matrix:\n", cirq.unitary(clock_op))
print("Shift matrix:\n", cirq.unitary(shift_op))


Clock matrix:
 [[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.30901699+0.95105652j  0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j         -0.80901699+0.58778525j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  -0.80901699-0.58778525j  0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.30901699-0.95105652j]]
Shift matrix:
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


Amelie Schreiber:

And, the code works!

In [17]:
import cirq
import numpy as np

def controlled_clock(n: int, control: cirq.Qid, target: cirq.Qid):
    # Define the clock matrix
    clock_mat = np.zeros((n, n), dtype=np.complex128)
    for i in range(n):
        clock_mat[i, i] = np.exp(2j * np.pi * i / n)
    clock_op = cirq.MatrixGate(clock_mat, qid_shape=(n,))

    # Define the controlled clock gate
    cclock_op = cirq.ControlledGate(clock_op, num_controls=1)

    # Define the circuit
    circuit = cirq.Circuit()
    circuit.append(cclock_op(control, target))

    return circuit



In [19]:
n = 5
control = cirq.LineQubit(0)
target = cirq.LineQid(1, dimension=n)

circuit = controlled_clock(n, control, target)
print(circuit)


0: ─────────@─────────────────────────────────────────────────────────────────────────
            │
            ┌                                                                     ┐
            │ 1.   +0.j     0.   +0.j     0.   +0.j     0.   +0.j     0.   +0.j   │
            │ 0.   +0.j     0.309+0.951j  0.   +0.j     0.   +0.j     0.   +0.j   │
1 (d=5): ───│ 0.   +0.j     0.   +0.j    -0.809+0.588j  0.   +0.j     0.   +0.j   │───
            │ 0.   +0.j     0.   +0.j     0.   +0.j    -0.809-0.588j  0.   +0.j   │
            │ 0.   +0.j     0.   +0.j     0.   +0.j     0.   +0.j     0.309-0.951j│
            └                                                                     ┘


In [25]:
import cirq
import numpy as np

def controlled_clock(n: int, control: cirq.Qid, target: cirq.Qid):
    # Define the clock matrix
    clock_mat = np.zeros((n, n), dtype=np.complex128)
    for i in range(n):
        clock_mat[i, i] = np.exp(2j * np.pi * i / n)
    clock_op = cirq.MatrixGate(clock_mat, qid_shape=(n,))

    # Define the controlled clock gate
    cclock_op = cirq.ControlledGate(clock_op, num_controls=1)

    # Define the circuit
    circuit = cirq.Circuit()
    circuit.append(cclock_op(control, target))

    return circuit

# Define the qudit and qubit
n = 5
control = cirq.LineQubit(0)
target = cirq.LineQid(1, dimension=n)

# Create the circuit
circuit = controlled_clock(n, control, target)

# Get the matrix of the circuit
unitary = circuit.unitary()

# Print the matrix
print("Controlled Clock Matrix Gate:")
print(unitary)


Controlled Clock Matrix Gate:
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          1.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          1.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   0